// Shared region/appellation knowledge base. Single source of truth for both
// lib/import/claude-extractor.ts's column-split detection (deciding whether
// a whole spreadsheet column should be offered as a "split this?" checkbox)
// and lib/wines/normalize.ts's per-value normalization — previously these
// lived as two separate, divergence-prone dictionaries.

// Region -> known sub-regions/appellations nested under it. Lowercase keys
// and values throughout.
export const REGION_SUBREGION_PAIRS: Record<string, string[]> = {
  'napa valley': ['oakville', 'rutherford', 'st. helena', 'stags leap', 'calistoga', 'yountville', 'howell mountain', 'atlas peak', 'spring mountain', 'diamond mountain', 'los carneros', 'mount veeder', 'coombsville', 'chiles valley'],
  'sonoma': ['russian river valley', 'sonoma coast', 'alexander valley', 'dry creek valley', 'knights valley', 'sonoma mountain', 'sonoma valley', 'bennett valley', 'chalk hill', 'green valley', 'moon mountain', 'petaluma gap', 'pine mountain-cloverdale peak'],
  'bordeaux': ['pauillac', 'margaux', 'saint-julien', 'saint-estèphe', 'pessac-léognan', 'saint-émilion', 'pomerol', 'médoc', 'haut-médoc', 'graves', 'sauternes', 'barsac', 'entre-deux-mers', 'fronsac', 'côtes de bourg'],
  'burgundy': ['chablis', 'côte de nuits', 'côte de beaune', 'côte chalonnaise', 'mâconnais', 'gevrey-chambertin', 'vosne-romanée', 'nuits-saint-georges', 'meursault', 'puligny-montrachet', 'chassagne-montrachet', 'pommard', 'volnay', 'beaune', 'corton', 'pouilly-fuissé'],
  'rhône': ['châteauneuf-du-pape', 'hermitage', 'côte-rôtie', 'gigondas', 'vacqueyras', 'crozes-hermitage', 'saint-joseph', 'condrieu', 'tavel', 'lirac', 'rasteau', 'vinsobres', 'cornas'],
  'tuscany': ['chianti', 'chianti classico', 'brunello di montalcino', 'bolgheri', 'montepulciano', 'montalcino', 'san gimignano', 'maremma'],
  'piedmont': ['barolo', 'barbaresco', 'langhe', 'roero', 'gavi', 'asti', 'alba'],
  'rioja': ['rioja alta', 'rioja alavesa', 'rioja baja', 'rioja oriental'],
  'willamette valley': ['dundee hills', 'eola-amity hills', 'yamhill-carlton', 'ribbon ridge', 'chehalem mountains', 'mcminnville'],
  'russian river valley': ['green valley', 'middle reach', 'east side'],
  'paso robles': ['adelaida district', 'willow creek', 'templeton gap', 'estrella district', 'geneseo district'],
  'santa barbara': ['santa ynez valley', 'sta. rita hills', 'happy canyon', 'los olivos district', 'ballard canyon'],
  'champagne': ['montagne de reims', 'côte des blancs', 'vallée de la marne', 'côte des bar', 'aube'],
  'loire': ['sancerre', 'vouvray', 'pouilly-fumé', 'chinon', 'saumur', 'muscadet'],
  'washington': ['columbia valley', 'walla walla valley', 'red mountain', 'yakima valley', 'horse heaven hills'],
  'mosel': ['bernkastel', 'piesport', 'wehlen', 'graach'],
  'barossa': ['barossa valley', 'eden valley'],
}

// Country -> known states/provinces/regions treated as "state" level.
export const COUNTRY_STATE_PAIRS: Record<string, string[]> = {
  'united states': ['california', 'oregon', 'washington', 'new york', 'virginia', 'texas', 'michigan', 'colorado', 'idaho', 'missouri', 'north carolina', 'ohio', 'pennsylvania', 'arizona', 'new mexico', 'maryland', 'georgia', 'illinois', 'indiana', 'iowa', 'minnesota', 'new jersey', 'connecticut', 'massachusetts'],
  'usa': ['california', 'oregon', 'washington', 'new york', 'virginia', 'texas', 'michigan', 'colorado', 'idaho', 'missouri'],
  'us': ['california', 'oregon', 'washington', 'new york', 'virginia', 'texas', 'michigan', 'colorado', 'idaho', 'missouri'],
  'australia': ['south australia', 'victoria', 'new south wales', 'western australia', 'tasmania', 'queensland'],
  'canada': ['british columbia', 'ontario', 'nova scotia', 'quebec'],
  'argentina': ['mendoza', 'salta', 'patagonia', 'san juan'],
  'germany': ['mosel', 'rheingau', 'pfalz', 'rheinhessen', 'baden', 'franken', 'nahe', 'württemberg', 'sachsen'],
  'italy': ['tuscany', 'piedmont', 'veneto', 'sicily', 'sardinia', 'lombardy', 'friuli', 'campania', 'puglia', 'trentino', 'alto adige', 'abruzzo', 'umbria', 'marche', 'liguria', 'emilia-romagna'],
  'spain': ['rioja', 'ribera del duero', 'priorat', 'galicia', 'catalonia', 'andalusia', 'castilla y león', 'navarra', 'valencia'],
  'france': ['bordeaux', 'burgundy', 'champagne', 'rhône', 'loire', 'alsace', 'languedoc', 'provence', 'jura', 'savoie', 'corsica', 'beaujolais'],
  'new zealand': ['marlborough', 'central otago', 'hawke\'s bay', 'martinborough', 'waiheke island', 'gisborne', 'wairarapa'],
  'south africa': ['stellenbosch', 'franschhoek', 'paarl', 'swartland', 'constantia', 'walker bay', 'elgin'],
  'chile': ['maipo valley', 'colchagua', 'casablanca', 'rapel', 'aconcagua', 'bio bio', 'itata'],
  'portugal': ['douro', 'alentejo', 'dão', 'bairrada', 'vinho verde', 'lisbon'],
}

// Misspellings/non-standard capitalization -> corrected form. Keys are
// lowercase; values are the display-correct form.
export const REGION_SPELLING_CORRECTIONS: Record<string, string> = {
  'chateauneuf-de-pape': 'Châteauneuf-du-Pape',
  'chateauneuf du pape': 'Châteauneuf-du-Pape',
  'chateauneuf-du-pape': 'Châteauneuf-du-Pape',
  'chateauneuf': 'Châteauneuf-du-Pape',
  'napa valley': 'Napa Valley',
  'sonoma county': 'Sonoma County',
  'sonoma': 'Sonoma County',
  'st helena': 'St. Helena',
  'saint helena': 'St. Helena',
  'stags leap': 'Stags Leap District',
  'stags leap district': 'Stags Leap District',
  'willamette valley': 'Willamette Valley',
  'willamette': 'Willamette Valley',
  'cotes du rhone': 'Côtes du Rhône',
  'côtes du rhone': 'Côtes du Rhône',
  'burgandy': 'Burgundy',
  'burgundy': 'Burgundy',
  'bordeaux': 'Bordeaux',
  'medoc': 'Médoc',
  'saint emilion': 'Saint-Émilion',
  'st emilion': 'Saint-Émilion',
  'st. emilion': 'Saint-Émilion',
  'pessac leognan': 'Pessac-Léognan',
  'gevrey chambertin': 'Gevrey-Chambertin',
  'vosne romanee': 'Vosne-Romanée',
  'nuits st georges': 'Nuits-Saint-Georges',
  'nuits-st-georges': 'Nuits-Saint-Georges',
  'puligny montrachet': 'Puligny-Montrachet',
  'cote rotie': 'Côte-Rôtie',
  'cote-rotie': 'Côte-Rôtie',
  'chianti classico': 'Chianti Classico',
  'brunello di montalcino': 'Brunello di Montalcino',
  'rioja alta': 'Rioja Alta',
  'rioja alavesa': 'Rioja Alavesa',
  'rioja baja': 'Rioja Oriental',
  'rioja oriental': 'Rioja Oriental',
  'columbia valley': 'Columbia Valley',
  'walla walla': 'Walla Walla Valley',
  'walla walla valley': 'Walla Walla Valley',
  'russian river': 'Russian River Valley',
  'russian river valley': 'Russian River Valley',
  'dry creek': 'Dry Creek Valley',
  'dry creek valley': 'Dry Creek Valley',
  'alexander valley': 'Alexander Valley',
  'rheingau': 'Rheingau',
  'mosel': 'Mosel',
  'moselle': 'Mosel',
  'rhône': 'Rhône Valley',
  'rhone': 'Rhône Valley',
  'rhône valley': 'Rhône Valley',
  'rhone valley': 'Rhône Valley',
  'tuscany': 'Tuscany',
  'piedmont': 'Piedmont',
  'rioja': 'Rioja',
  'champagne': 'Champagne',
  'loire': 'Loire Valley',
  'loire valley': 'Loire Valley',
  'barossa': 'Barossa',
  'washington': 'Washington',
}

// Normalized (lowercase) sub-region name -> full legal appellation
// designation. Deliberately a direct lookup rather than a generic
// "append AVA/AOC" suffix rule — Italian DOCG names in particular bundle a
// wine name with the place name (Brunello di Montalcino DOCG, not
// "Montalcino DOCG"), which a suffix rule would get wrong.
export const KNOWN_APPELLATIONS: Record<string, string> = {
  'stags leap district': 'Stags Leap District AVA',
  'oakville': 'Oakville AVA',
  'rutherford': 'Rutherford AVA',
  'howell mountain': 'Howell Mountain AVA',
  'st. helena': 'St. Helena AVA',
  'calistoga': 'Calistoga AVA',
  'yountville': 'Yountville AVA',
  'atlas peak': 'Atlas Peak AVA',
  'spring mountain': 'Spring Mountain District AVA',
  'diamond mountain': 'Diamond Mountain District AVA',
  'mount veeder': 'Mount Veeder AVA',
  'coombsville': 'Coombsville AVA',
  'russian river valley': 'Russian River Valley AVA',
  'alexander valley': 'Alexander Valley AVA',
  'dry creek valley': 'Dry Creek Valley AVA',
  'knights valley': 'Knights Valley AVA',
  'chalk hill': 'Chalk Hill AVA',
  'bennett valley': 'Bennett Valley AVA',
  'sonoma valley': 'Sonoma Valley AVA',
  'sonoma coast': 'Sonoma Coast AVA',
  'dundee hills': 'Dundee Hills AVA',
  'eola-amity hills': 'Eola-Amity Hills AVA',
  'yamhill-carlton': 'Yamhill-Carlton AVA',
  'ribbon ridge': 'Ribbon Ridge AVA',
  'columbia valley': 'Columbia Valley AVA',
  'walla walla valley': 'Walla Walla Valley AVA',
  'red mountain': 'Red Mountain AVA',
  'yakima valley': 'Yakima Valley AVA',
  'châteauneuf-du-pape': 'Châteauneuf-du-Pape AOC',
  'hermitage': 'Hermitage AOC',
  'côte-rôtie': 'Côte-Rôtie AOC',
  'gigondas': 'Gigondas AOC',
  'condrieu': 'Condrieu AOC',
  'pauillac': 'Pauillac AOC',
  'margaux': 'Margaux AOC',
  'saint-julien': 'Saint-Julien AOC',
  'saint-estèphe': 'Saint-Estèphe AOC',
  'pessac-léognan': 'Pessac-Léognan AOC',
  'saint-émilion': 'Saint-Émilion AOC',
  'pomerol': 'Pomerol AOC',
  'sauternes': 'Sauternes AOC',
  'gevrey-chambertin': 'Gevrey-Chambertin AOC',
  'vosne-romanée': 'Vosne-Romanée AOC',
  'meursault': 'Meursault AOC',
  'puligny-montrachet': 'Puligny-Montrachet AOC',
  'pommard': 'Pommard AOC',
  'chablis': 'Chablis AOC',
  'montalcino': 'Brunello di Montalcino DOCG',
  'chianti classico': 'Chianti Classico DOCG',
  'barolo': 'Barolo DOCG',
  'barbaresco': 'Barbaresco DOCG',
  'rioja alta': 'Rioja DOCa',
  'rioja alavesa': 'Rioja DOCa',
  'rioja oriental': 'Rioja DOCa',
  'rioja': 'Rioja DOCa',
}

// Sub-regions that legitimately mean different things depending on context
// (e.g. Carneros straddles Napa and Sonoma) — normalizeRegionAndSubRegion
// returns these unchanged with `ambiguous: true` rather than guessing.
export const AMBIGUOUS_SUBREGIONS = new Set<string>(['carneros', 'los carneros', 'sonoma valley'])
