// Canonical varietal names and their known shortcuts/misspellings/synonyms.
// Keys are lowercase-normalized (trim + lowercase) variants; values are the
// canonical display form. Approved in the wine-data-normalization diagnostic
// session — see conversation history for the full reasoning behind each
// mapping, especially the "same grape, different regional name" cases
// (Zinfandel/Primitivo, Syrah/Shiraz, Grenache/Cannonau) that ARE merged here,
// and the deliberately-NOT-merged near-collisions noted inline below.
export const VARIETAL_MAP: Record<string, string> = {
  // Reds
  'cabernet sauvignon': 'Cabernet Sauvignon',
  'cab sauv': 'Cabernet Sauvignon',
  'cab': 'Cabernet Sauvignon',
  'cabernet': 'Cabernet Sauvignon',
  'cs': 'Cabernet Sauvignon',
  'merlot': 'Merlot',
  'merlo': 'Merlot',
  'pinot noir': 'Pinot Noir',
  'pino noir': 'Pinot Noir',
  'pn': 'Pinot Noir',
  'pinot': 'Pinot Noir',
  'spätburgunder': 'Pinot Noir',
  'spatburgunder': 'Pinot Noir',
  'blauburgunder': 'Pinot Noir',
  'syrah': 'Syrah',
  'shiraz': 'Shiraz',
  'sangiovese': 'Sangiovese',
  'sangioveto': 'Sangiovese',
  'prugnolo gentile': 'Sangiovese',
  'morellino': 'Sangiovese',
  'nebbiolo': 'Nebbiolo',
  'spanna': 'Nebbiolo',
  'chiavennasca': 'Nebbiolo',
  'tempranillo': 'Tempranillo',
  'tinto fino': 'Tempranillo',
  'tinta del pais': 'Tempranillo',
  'tinta de toro': 'Tempranillo',
  'cencibel': 'Tempranillo',
  'ull de llebre': 'Tempranillo',
  'tinta roriz': 'Tempranillo',
  'aragonez': 'Tempranillo',
  'malbec': 'Malbec',
  'cot': 'Malbec',
  'côt': 'Malbec',
  'auxerrois': 'Malbec',
  'zinfandel': 'Zinfandel',
  'zin': 'Zinfandel',
  'primitivo': 'Primitivo',
  'grenache': 'Grenache',
  'garnacha': 'Grenache',
  'garnacha tinta': 'Grenache',
  'grenache noir': 'Grenache',
  'cannonau': 'Grenache',
  'mourvèdre': 'Mourvèdre',
  'mourvedre': 'Mourvèdre',
  'monastrell': 'Mourvèdre',
  'mataro': 'Mourvèdre',
  'carmenère': 'Carmenère',
  'carmenere': 'Carmenère',
  'grande vidure': 'Carmenère',
  'petite sirah': 'Petite Sirah',
  'petite syrah': 'Petite Sirah',
  'durif': 'Petite Sirah',
  'petit verdot': 'Petit Verdot',
  'p. verdot': 'Petit Verdot',
  'p verdot': 'Petit Verdot',
  'pv': 'Petit Verdot',
  'gamay': 'Gamay',
  'gamay noir': 'Gamay',
  'carignan': 'Carignan',
  'carignane': 'Carignan',
  'mazuelo': 'Carignan',
  'cariñena': 'Carignan',
  'carinena': 'Carignan',
  'samsó': 'Carignan',
  'samso': 'Carignan',
  'barbera': 'Barbera',
  "nero d'avola": "Nero d'Avola",
  'calabrese': "Nero d'Avola",
  'aglianico': 'Aglianico',
  'montepulciano': 'Montepulciano',
  'dolcetto': 'Dolcetto',
  'tannat': 'Tannat',
  'touriga nacional': 'Touriga Nacional',
  'pinotage': 'Pinotage',
  'blaufränkisch': 'Blaufränkisch',
  'blaufrankisch': 'Blaufränkisch',
  'lemberger': 'Blaufränkisch',
  'kékfrankos': 'Blaufränkisch',
  'kekfrankos': 'Blaufränkisch',
  'zweigelt': 'Zweigelt',
  'cabernet franc': 'Cabernet Franc',
  'cab franc': 'Cabernet Franc',
  'cf': 'Cabernet Franc',
  'bouchet': 'Cabernet Franc',

  // Whites
  'chardonnay': 'Chardonnay',
  'chard': 'Chardonnay',
  'pinot chardonnay': 'Chardonnay',
  'sauvignon blanc': 'Sauvignon Blanc',
  'sauv blanc': 'Sauvignon Blanc',
  'sb': 'Sauvignon Blanc',
  'fumé blanc': 'Sauvignon Blanc',
  'fume blanc': 'Sauvignon Blanc',
  'blanc fumé': 'Sauvignon Blanc',
  'blanc fume': 'Sauvignon Blanc',
  'riesling': 'Riesling',
  'reisling': 'Riesling',
  'pinot gris': 'Pinot Gris / Pinot Grigio',
  'pinot grigio': 'Pinot Gris / Pinot Grigio',
  'pg': 'Pinot Gris / Pinot Grigio',
  'grauburgunder': 'Pinot Gris / Pinot Grigio',
  'ruländer': 'Pinot Gris / Pinot Grigio',
  'rulander': 'Pinot Gris / Pinot Grigio',
  'viognier': 'Viognier',
  'albariño': 'Albariño',
  'albarino': 'Albariño',
  'alvarinho': 'Albariño',
  'chenin blanc': 'Chenin Blanc',
  'steen': 'Chenin Blanc',
  'gewürztraminer': 'Gewürztraminer',
  'gewurztraminer': 'Gewürztraminer',
  'traminer': 'Gewürztraminer',
  'sémillon': 'Sémillon',
  'semillon': 'Sémillon',
  'marsanne': 'Marsanne',
  'roussanne': 'Roussanne',
  'grüner veltliner': 'Grüner Veltliner',
  'gruner veltliner': 'Grüner Veltliner',
  'grüve': 'Grüner Veltliner',
  'gruve': 'Grüner Veltliner',
  'gv': 'Grüner Veltliner',
  'torrontés': 'Torrontés',
  'torrontes': 'Torrontés',
  'vermentino': 'Vermentino',
  'rolle': 'Vermentino',
  'pigato': 'Vermentino',
  'fiano': 'Fiano',
  'falanghina': 'Falanghina',
  'trebbiano': 'Trebbiano',
  'ugni blanc': 'Trebbiano',
  'procanico': 'Trebbiano',
  'garganega': 'Garganega',
  'arneis': 'Arneis',
  'cortese': 'Cortese',
  'verdejo': 'Verdejo',
  'godello': 'Godello',
  'furmint': 'Furmint',
  'müller-thurgau': 'Müller-Thurgau',
  'muller-thurgau': 'Müller-Thurgau',
  'muller thurgau': 'Müller-Thurgau',
  'rivaner': 'Müller-Thurgau',
  'sylvaner': 'Sylvaner',
  'silvaner': 'Sylvaner',
  'muscadet': 'Muscadet',
  'melon de bourgogne': 'Muscadet',
  'moscato': 'Moscato',
  'muscat': 'Moscato',
  'muscat blanc': 'Moscato',
  'moscato bianco': 'Moscato',
  'muscat canelli': 'Moscato',
  'friulano': 'Friulano',
  'ribolla gialla': 'Ribolla Gialla',
  'pecorino': 'Pecorino',

  // Rosé
  'rosé': 'Rosé',
  'rose': 'Rosé',
  'rosado': 'Rosé',
  'rosato': 'Rosé',
  'blush': 'Rosé',

  // Sparkling
  'champagne': 'Champagne',
  'blanc de blancs': 'Blanc de Blancs',
  'blanc de noirs': 'Blanc de Noirs',
  'pét-nat': 'Pét-Nat',
  'pet-nat': 'Pét-Nat',
  'petillant naturel': 'Pét-Nat',
  'pétillant naturel': 'Pét-Nat',
  'crémant': 'Sparkling Blend',
  'cremant': 'Sparkling Blend',
  'cava': 'Sparkling Blend',
  'sekt': 'Sparkling Blend',
  'spumante': 'Sparkling Blend',
  'prosecco': 'Sparkling Blend',
  'méthode traditionnelle': 'Sparkling Blend',
  'methode traditionnelle': 'Sparkling Blend',
  'metodo classico': 'Sparkling Blend',

  // Blends (individually normalized components only — whole-string blend
  // names are protected below and never reach this per-component lookup)
  'white blend': 'White Blend',
  'white bordeaux': 'White Blend',
  'white burgundy': 'White Blend',
  'white rhône blend': 'White Blend',
  'white rhone blend': 'White Blend',
  'red blend': 'Red Blend',
  'bordeaux blend': 'Bordeaux Blend',
  'rhône blend': 'Rhône Blend',
  'rhone blend': 'Rhône Blend',
  'meritage': 'Meritage',
  'gsm': 'GSM',
}

// Whole-string blend descriptors that must never be split or expanded — a
// user meant exactly this term, not a list of grapes. Checked case-
// insensitively against the ENTIRE input before any split-on-separator logic
// runs. Lowercase.
export const PROTECTED_BLEND_NAMES = new Set<string>([
  'gsm',
  'meritage',
  'bordeaux blend',
  'rhône blend',
  'rhone blend',
  'red blend',
  'white blend',
  'white bordeaux',
  'white burgundy',
  'white rhône blend',
  'white rhone blend',
  'sparkling blend',
  'super tuscan',
  'field blend',
  'proprietary red',
  'proprietary white',
])
